version: '3.8'

services:
 backend:
  build: .
  ports:
   - "5000:5000"
  volumes:
   - .:/app
   - ./uploads:/app/uploads
  environment:
   - NODE_ENV=development
  env_file:
   - .env
  depends_on:
   - db

 db:
  image: postgres:15
  environment:
   POSTGRES_DB: rentCar
   POSTGRES_USER: rentCar_admin
   POSTGRES_PASSWORD: rentCar_admin
  ports:
   - "5433:5432"
  volumes:
   - pgdata:/var/lib/postgresql/data
   - ./init-db:/docker-entrypoint-initdb.d

volumes:
 pgdata:
